### ISSUE TITLE
Not Loading. 

### ISSUE THREAD

**Issue by mshaque** [DavidMoore/ipfilter#13]
Tried using all the versions available. 

Thank you for all your hard work. 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IPFilter.UI.exe
  Application Version:	2.0.0.4
  Application Timestamp:	54be0f2e
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7c78c
  Exception Code:	e0434352
  Exception Offset:	000000000000a49d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	2413
  Additional Information 2:	2413de213f38e5efe700010a55469627
  Additional Information 3:	57bb
  Additional Information 4:	57bb597d10cfc54126c0a7d525027b8d

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.1
	System.Deployment.dll 		: 4.0.30319.1 (RTMRel.030319-0100)
	clr.dll 			: 4.0.30319.1 (RTMRel.030319-0100)
	dfdll.dll 			: 4.0.30319.1 (RTMRel.030319-0100)
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

SOURCES
	Deployment url			: file:///C:/Users/user1/Downloads/DavidMoore-ipfilter-a43eded%20(1)/DavidMoore-ipfilter-a43eded/install/IPFilter.UI.application
	Deployment Provider url		: https://davidmoore.github.io/IP-Filter-Updater/install/IPFilter.UI.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\user1\Downloads\DavidMoore-ipfilter-a43eded (1)\DavidMoore-ipfilter-a43eded\install\IPFilter.UI.application resulted in exception. Following failure messages were detected:
		+ Downloading https://davidmoore.github.io/IP-Filter-Updater/install/IPFilter.UI.application did not succeed.
		+ The remote server returned an error: (404) Not Found.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [4/5/2015 9:23:59 PM] : Activation of C:\Users\user1\Downloads\DavidMoore-ipfilter-a43eded (1)\DavidMoore-ipfilter-a43eded\install\IPFilter.UI.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [4/5/2015 9:23:59 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading https://davidmoore.github.io/IP-Filter-Updater/install/IPFilter.UI.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadManifest(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ManifestType manifestType, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (404) Not Found.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by DavidMoore** [comment]
New installer should be on the way soon, which will hopefully get rid of these install / deployment issues.

**Comment by DavidMoore** [comment]
Hi, please try the new installer at https://davidmoore.github.io/ipfilter/install/IPFilter.msi

**Comment by DavidMoore** [comment]
Please re-open this issue if you have any further problems with the new version
