### ISSUE TITLE
Auto Update No Longer Working

### ISSUE THREAD

**Issue by daveb3** [DavidMoore/ipfilter#18]
the auto update feature is no longer working in Windows 10 x64 but it was working fine in Windows 8.1 x64

can someone plz help me with this feature...

**Comment by DavidMoore** [comment]
Do you have a log you can attach or post in? Do you have version 2.0.0.4 already?

**Comment by BuckledToe** [comment]
Same problem here.
ErrorCode: 
Couldn't schedule automated update: Access is denied. (Exception from HRESULT: 0x80070005 (EACCESSDENI

**Comment by BuckledToe** [comment]
Setting up the automatic schedule...
Couldn't schedule automated update: System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String Path, TaskDefinition definition, TaskCreation createType, String UserId, String password, TaskLogonType LogonType, String sddl)
   at IPFilter.ViewModels.OptionsViewModel.SaveSettings(Object o) in c:\Projects\IPFilterUpdater\master\Code\IPFilter\ViewModels\OptionsViewModel.cs:line 128

**Comment by gavsiu** [comment]
Same issue here. Is this app updated anymore?

**Comment by madhatr** [comment]
I get the same issues, it has to do with not running the program elevated.  Though when I try to run as Admin the program does not open.

**Comment by DavidMoore** [comment]
This one's a bit tricky to troubleshoot because it's hard to test on my machine without updating the live version (due to the install permissions). I've got a probably fix to push live which I'll try to do very soon, trying not to break the app in the process as I've been working on the auto-update of the app itself.
