### ISSUE TITLE
Doesn't work with Japanese paths

### ISSUE THREAD

**Issue by molitar** [DavidMoore/ipfilter#27]
Faulting application name: IPFilter.exe, version: 2.2.2.0, time stamp: 0x5731b7df
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23392, time stamp: 0x56eb3604
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0x410
Faulting application start time: 0x01d1e237d278ebca
Faulting application path: C:\Users\malaac\AppData\Local\IPFilter\IPFilter.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 10fd99fe-4e2b-11e6-8da9-1c872c768ec6

Application: IPFilter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.DirectoryInfo.Init(System.String, Boolean)
   at IPFilter.Apps.BitTorrentApplication+<DetectAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at IPFilter.Apps.ApplicationEnumerator+<GetInstalledApplications>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at IPFilter.ViewModels.MainWindowViewModel+<Initialize>d__81.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IPFilter.Views.MainWindow+<Window_Loaded>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at IPFilter.EntryPoint.Main(System.String[])

**Comment by DavidMoore** [comment]
Hi @molitar . How comfortable are you with the Windows Registry? It looks like it's finding where BitTorrent is installed from the Windows Registry, and then trying to resolve that to the folder on the disk. And that's where it fails. If not, I can always add some more logging to nail this down.

**Comment by molitar** [comment]
I am very comfortable with the registry.  I use to do Dell Poweredge Server Support until it moved to Bangalore now I do ProSupport.  Though I am now using qBitTorrent got tired of all the bloat in uTorrent

**Comment by DavidMoore** [comment]
Did you still have the problematic uTorrent installed? The install location is in the registry at "Software\Microsoft\Windows\CurrentVersion\Uninstall\uTorrent" (or at least it used to be). Check both HKLM and HKCU, and also when you're under the HKLM key, it's probably going to be in the 32 bit registry "Software\**WOW6432Node**\Microsoft\Windows\CurrentVersion\Uninstall\".

If you find that key, what is the InstallLocation value set to under there? .NET seems to not like parsing the path that's in that.

**Comment by DavidMoore** [comment]
I'm going to close this issue but please re-open or log a new one if you run into this still

**Comment by DavidMoore** [comment]
Hi @molitar , I've re-opened this issue. Can you please check the InstallLocation in the registry as I noted just above?

**Comment by molitar** [comment]
Hi David.

UninstallString  "C:¥Program Files¥qBittorrent¥uninst.exe"

That is under the latter path Wow6432Node and is correct path. BTW I run in Japanese Locale mode so backslashes show as the Yen symbol by Microsoft.

**Comment by DavidMoore** [comment]
Hi @molitar . Are you able to test version 3.0.2 please? If it still crashes, the log should provide more details.

**Comment by molitar** [comment]
Hi DavidMoore,

Tried to download the new master and ran the file IPFilter.UI.application and the error below happened.
 
"Cannot download the application. The application is missing required files. Contact application vendor for assistance."

`PLATFORM VERSION INFO
	Windows 			: 10.0.17133.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.3761.0 built by: NET48REL1
	clr.dll 			: 4.8.3761.0 built by: NET48REL1
	dfdll.dll 			: 4.8.3761.0 built by: NET48REL1
	dfshim.dll 			: 10.0.17133.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Downloads/ipfilter-master/install/Application%20Files/IPFilter.UI_1_0_0_10/IPFilter.UI.application
	Deployment Provider url		: https://davidmoore.github.io/IP-Filter-Updater/install/IPFilter.UI.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Downloads\ipfilter-master\install\Application Files\IPFilter.UI_1_0_0_10\IPFilter.UI.application resulted in exception. Following failure messages were detected:
		+ Downloading https://davidmoore.github.io/IP-Filter-Updater/install/IPFilter.UI.application did not succeed.
		+ The remote server returned an error: (404) Not Found.`

**Comment by DavidMoore** [comment]
Hi! Please download and run https://github.com/DavidMoore/ipfilter/releases/download/3.0.2.3-beta/IPFilter.msi

**Comment by molitar** [comment]
Hi DavidMoore that worked great and the log shows it wrote the file to the correct folder location for QBitTorrent.  Looks like the problem is resolved.  Thanks

**Comment by DavidMoore** [comment]
Great! Thanks for your help, and your patience @molitar :)
